# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/goghvmu/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/goghvmu/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/samsung/goghvmu/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/samsung/goghvmu/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/samsung/goghvmu/proprietary/bin/thermald:system/bin/thermald \
    vendor/samsung/goghvmu/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/samsung/goghvmu/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/samsung/goghvmu/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
    vendor/samsung/goghvmu/proprietary/lib/libdivxdrm.so:system/lib/libdivxdrm.so \
    vendor/samsung/goghvmu/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/samsung/goghvmu/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/samsung/goghvmu/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/samsung/goghvmu/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/samsung/goghvmu/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/samsung/goghvmu/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/samsung/goghvmu/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/samsung/goghvmu/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/samsung/goghvmu/proprietary/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
    vendor/samsung/goghvmu/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/samsung/goghvmu/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/samsung/goghvmu/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/samsung/goghvmu/proprietary/lib/libllvm-a3xx.so:system/lib/libllvm-a3xx.so \
    vendor/samsung/goghvmu/proprietary/lib/libsc-a3xx.so:system/lib/libsc-a3xx.so \
    vendor/samsung/goghvmu/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/samsung/goghvmu/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/samsung/goghvmu/proprietary/lib/libOpenCL.so:system/lib/libOpenCL.so \
    vendor/samsung/goghvmu/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/samsung/goghvmu/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/samsung/goghvmu/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/samsung/goghvmu/proprietary/lib/libI420colorconvert.so:system/lib/libI420colorconvert.so \
    vendor/samsung/goghvmu/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/samsung/goghvmu/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/samsung/goghvmu/proprietary/lib/libmm-abl-oem.so:system/lib/libmm-abl-oem.so \
    vendor/samsung/goghvmu/proprietary/lib/libNimsWrap.so:system/lib/libNimsWrap.so \
    vendor/samsung/goghvmu/proprietary/lib/libcnefeatureconfig.so:system/lib/libcnefeatureconfig.so \
    vendor/samsung/goghvmu/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/samsung/goghvmu/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/goghvmu/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/goghvmu/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/goghvmu/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/goghvmu/proprietary/lib/libcordon.so:system/lib/libcordon.so \
    vendor/samsung/goghvmu/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/samsung/goghvmu/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/samsung/goghvmu/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/samsung/goghvmu/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/goghvmu/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/samsung/goghvmu/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/samsung/goghvmu/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/goghvmu/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/goghvmu/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/samsung/goghvmu/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/samsung/goghvmu/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/goghvmu/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/samsung/goghvmu/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
    vendor/samsung/goghvmu/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/samsung/goghvmu/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
    vendor/samsung/goghvmu/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
    vendor/samsung/goghvmu/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
    vendor/samsung/goghvmu/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/samsung/goghvmu/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/samsung/goghvmu/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/samsung/goghvmu/proprietary/lib/libtime_genoff.so:system/lib/libtime_genoff.so \
    vendor/samsung/goghvmu/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/samsung/goghvmu/proprietary/lib/libgeofence.so:system/lib/libgeofence.so \
    vendor/samsung/goghvmu/proprietary/bin/geomagneticd:system/bin/geomagneticd \
    vendor/samsung/goghvmu/proprietary/bin/orientationd:system/bin/orientationd \
    vendor/samsung/goghvmu/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
    vendor/samsung/goghvmu/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/samsung/goghvmu/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
    vendor/samsung/goghvmu/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/goghvmu/proprietary/lib/hw/camera.msm8960.so:system/lib/hw/camera.msm8960.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_mt9e013_default_video.so:system/lib/libchromatix_mt9e013_default_video.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_mt9e013_preview.so:system/lib/libchromatix_mt9e013_preview.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_vx6953_default_video.so:system/lib/libchromatix_vx6953_default_video.so \
    vendor/samsung/goghvmu/proprietary/lib/libchromatix_vx6953_preview.so:system/lib/libchromatix_vx6953_preview.so \
    vendor/samsung/goghvmu/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/samsung/goghvmu/proprietary/lib/libimage-jpeg-dec-omx-comp.so:system/lib/libimage-jpeg-dec-omx-comp.so \
    vendor/samsung/goghvmu/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/samsung/goghvmu/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/samsung/goghvmu/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/samsung/goghvmu/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/samsung/goghvmu/proprietary/lib/libmmcamera_statsproc30.so:system/lib/libmmcamera_statsproc30.so \
    vendor/samsung/goghvmu/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/samsung/goghvmu/proprietary/lib/libmmmpod.so:system/lib/libmmmpod.so \
    vendor/samsung/goghvmu/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/samsung/goghvmu/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/samsung/goghvmu/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/goghvmu/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/samsung/goghvmu/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/samsung/goghvmu/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/samsung/goghvmu/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/samsung/goghvmu/proprietary/lib/libhdcp2.so:system/lib/libhdcp2.so \
    vendor/samsung/goghvmu/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/samsung/goghvmu/proprietary/lib/libWVStreamControlAPI_L3.so:system/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/goghvmu/proprietary/lib/libtzplayready.so:system/lib/libtzplayready.so \
    vendor/samsung/goghvmu/proprietary/lib/libwvm.so:system/lib/libwvm.so
